# Generated by Django 6.0.4 on 2026-05-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('gradient', models.CharField(max_length=100)),
                ('bookmarked', models.BooleanField(default=False)),
                ('min_gwa', models.FloatField()),
                ('max_income', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
