# Generated by Django 6.0.4 on 2026-05-16 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='course',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.TextField(),
        ),
    ]
